<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="maquette" nsURI="fs://maquette" nsPrefix="maquette">
  <eClassifiers xsi:type="ecore:EClass" name="Formation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbSemestres" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semestres" upperBound="-1"
        eType="#//Semestre" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="compétencesEnseignées"
        upperBound="-1" eType="#//Compétence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uesPotentielles" upperBound="-1"
        eType="#//UE" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Semestre">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbECTS" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" defaultValueLiteral="30"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numero" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ues" upperBound="-1" eType="#//UE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UE">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbECTS" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="compétence" upperBound="-1"
        eType="#//Compétence" eOpposite="#//Compétence/ues"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="disciplinaire" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Compétence">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ues" upperBound="-1" eType="#//UE"
        eOpposite="#//UE/compétence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Formations">
    <eStructuralFeatures xsi:type="ecore:EReference" name="formations" upperBound="-1"
        eType="#//Formation" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
