<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="objetPersonnalisablePackage" nsURI="http://objetPersonnalisable/1.0"
    nsPrefix="objetPersonnalisable">
  <eClassifiers xsi:type="ecore:EClass" name="GammePersonnalisable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objets" upperBound="-1"
        eType="#//Objet" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementsdepersonnalisation"
        upperBound="-1" eType="#//ElementDePersonnalisation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementsvariables" upperBound="-1"
        eType="#//CaracteristiqueVariable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Objet" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="CaracteristiqueVariable" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementDePersonnalisation" eSuperTypes="#//NamedElement"/>
</ecore:EPackage>
